# Generated by Django 4.2.16 on 2024-09-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tag_tasks_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
